packages:
  - packages/*

catalog:
  '@biomejs/biome': 2.4.7
  '@types/node': ^25.5.0
  tsup: ^8.5.1
  tsx: ^4.21.0
  typescript: 5.9.3

catalogMode: prefer

cleanupUnusedCatalogs: true

engineStrict: true

minimumReleaseAge: 10080

overrides:
  chokidar: ^5.0.0

trustPolicy: no-downgrade
