type UnaryFn<In, Out> = (input: In) => Out;
export type Seq = {
  <A>(value: A): A;
  <A, B>(value: A, f1: UnaryFn<A, B>): B;
  <A, B, C>(value: A, f1: UnaryFn<A, B>, f2: UnaryFn<B, C>): C;
  <A, B, C, D>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
  ): D;
  <A, B, C, D, E>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
  ): E;
  <A, B, C, D, E, F>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
  ): F;
  <A, B, C, D, E, F, G>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
  ): G;
  <A, B, C, D, E, F, G, H>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
  ): H;
  <A, B, C, D, E, F, G, H, I>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
    f8: UnaryFn<H, I>,
  ): I;
  <A, B, C, D, E, F, G, H, I, J>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
    f8: UnaryFn<H, I>,
    f9: UnaryFn<I, J>,
  ): J;
  <A, B, C, D, E, F, G, H, I, J, K>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
    f8: UnaryFn<H, I>,
    f9: UnaryFn<I, J>,
    f10: UnaryFn<J, K>,
  ): K;
  <A, B, C, D, E, F, G, H, I, J, K, L>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
    f8: UnaryFn<H, I>,
    f9: UnaryFn<I, J>,
    f10: UnaryFn<J, K>,
    f11: UnaryFn<K, L>,
  ): L;
  <A, B, C, D, E, F, G, H, I, J, K, L, M>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
    f8: UnaryFn<H, I>,
    f9: UnaryFn<I, J>,
    f10: UnaryFn<J, K>,
    f11: UnaryFn<K, L>,
    f12: UnaryFn<L, M>,
  ): M;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
    f8: UnaryFn<H, I>,
    f9: UnaryFn<I, J>,
    f10: UnaryFn<J, K>,
    f11: UnaryFn<K, L>,
    f12: UnaryFn<L, M>,
    f13: UnaryFn<M, N>,
  ): N;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
    f8: UnaryFn<H, I>,
    f9: UnaryFn<I, J>,
    f10: UnaryFn<J, K>,
    f11: UnaryFn<K, L>,
    f12: UnaryFn<L, M>,
    f13: UnaryFn<M, N>,
    f14: UnaryFn<N, O>,
  ): O;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
    f8: UnaryFn<H, I>,
    f9: UnaryFn<I, J>,
    f10: UnaryFn<J, K>,
    f11: UnaryFn<K, L>,
    f12: UnaryFn<L, M>,
    f13: UnaryFn<M, N>,
    f14: UnaryFn<N, O>,
    f15: UnaryFn<O, P>,
  ): P;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
    value: A,
    f1: UnaryFn<A, B>,
    f2: UnaryFn<B, C>,
    f3: UnaryFn<C, D>,
    f4: UnaryFn<D, E>,
    f5: UnaryFn<E, F>,
    f6: UnaryFn<F, G>,
    f7: UnaryFn<G, H>,
    f8: UnaryFn<H, I>,
    f9: UnaryFn<I, J>,
    f10: UnaryFn<J, K>,
    f11: UnaryFn<K, L>,
    f12: UnaryFn<L, M>,
    f13: UnaryFn<M, N>,
    f14: UnaryFn<N, O>,
    f15: UnaryFn<O, P>,
    f16: UnaryFn<P, Q>,
  ): Q;
};

type UnaryAsyncFn<In, Out> = UnaryFn<Awaited<In>, Out | Promise<Out>>;
export type SeqAsync = {
  <A>(value: A): Promise<A>;
  <A, B>(value: A, f1: UnaryAsyncFn<A, B>): Promise<B>;
  <A, B, C>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
  ): Promise<C>;
  <A, B, C, D>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
  ): Promise<D>;
  <A, B, C, D, E>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
  ): Promise<E>;
  <A, B, C, D, E, F>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
  ): Promise<F>;
  <A, B, C, D, E, F, G>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
  ): Promise<G>;
  <A, B, C, D, E, F, G, H>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
  ): Promise<H>;
  <A, B, C, D, E, F, G, H, I>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
    f8: UnaryAsyncFn<H, I>,
  ): Promise<I>;
  <A, B, C, D, E, F, G, H, I, J>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
    f8: UnaryAsyncFn<H, I>,
    f9: UnaryAsyncFn<I, J>,
  ): Promise<J>;
  <A, B, C, D, E, F, G, H, I, J, K>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
    f8: UnaryAsyncFn<H, I>,
    f9: UnaryAsyncFn<I, J>,
    f10: UnaryAsyncFn<J, K>,
  ): Promise<K>;
  <A, B, C, D, E, F, G, H, I, J, K, L>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
    f8: UnaryAsyncFn<H, I>,
    f9: UnaryAsyncFn<I, J>,
    f10: UnaryAsyncFn<J, K>,
    f11: UnaryAsyncFn<K, L>,
  ): Promise<L>;
  <A, B, C, D, E, F, G, H, I, J, K, L, M>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
    f8: UnaryAsyncFn<H, I>,
    f9: UnaryAsyncFn<I, J>,
    f10: UnaryAsyncFn<J, K>,
    f11: UnaryAsyncFn<K, L>,
    f12: UnaryAsyncFn<L, M>,
  ): Promise<M>;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
    f8: UnaryAsyncFn<H, I>,
    f9: UnaryAsyncFn<I, J>,
    f10: UnaryAsyncFn<J, K>,
    f11: UnaryAsyncFn<K, L>,
    f12: UnaryAsyncFn<L, M>,
    f13: UnaryAsyncFn<M, N>,
  ): Promise<N>;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
    f8: UnaryAsyncFn<H, I>,
    f9: UnaryAsyncFn<I, J>,
    f10: UnaryAsyncFn<J, K>,
    f11: UnaryAsyncFn<K, L>,
    f12: UnaryAsyncFn<L, M>,
    f13: UnaryAsyncFn<M, N>,
    f14: UnaryAsyncFn<N, O>,
  ): Promise<O>;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
    f8: UnaryAsyncFn<H, I>,
    f9: UnaryAsyncFn<I, J>,
    f10: UnaryAsyncFn<J, K>,
    f11: UnaryAsyncFn<K, L>,
    f12: UnaryAsyncFn<L, M>,
    f13: UnaryAsyncFn<M, N>,
    f14: UnaryAsyncFn<N, O>,
    f15: UnaryAsyncFn<O, P>,
  ): Promise<P>;
  <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
    value: A,
    f1: UnaryAsyncFn<A, B>,
    f2: UnaryAsyncFn<B, C>,
    f3: UnaryAsyncFn<C, D>,
    f4: UnaryAsyncFn<D, E>,
    f5: UnaryAsyncFn<E, F>,
    f6: UnaryAsyncFn<F, G>,
    f7: UnaryAsyncFn<G, H>,
    f8: UnaryAsyncFn<H, I>,
    f9: UnaryAsyncFn<I, J>,
    f10: UnaryAsyncFn<J, K>,
    f11: UnaryAsyncFn<K, L>,
    f12: UnaryAsyncFn<L, M>,
    f13: UnaryAsyncFn<M, N>,
    f14: UnaryAsyncFn<N, O>,
    f15: UnaryAsyncFn<O, P>,
    f16: UnaryAsyncFn<P, Q>,
  ): Promise<Q>;
};
